name: chartjs
version: 0.5.2
description: Chart.js wrapper for Dart
homepage: https://github.com/google/chartjs.dart/
environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  js: ^0.6.3

dev_dependencies:
  build_runner: ^2.1.2
  build_web_compilers: ^3.2.1
  lints: ^1.0.0
